// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zsoqkzlycvhiqqgdkdlh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpzb3Fremx5Y3ZoaXFxZ2RrZGxoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTMyNTgsImV4cCI6MjA1OTc2OTI1OH0.ciHN2-yPbugkm7ZPi3RaKCb49SAx6BpxWsSmDQTfnu4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);